apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-prediction
  template:
    metadata:
      labels:
        app: churn-prediction
    spec:
      containers:
      - name: churn-prediction
        image: mlchurnprediction.azurecr.io/churn-prediction:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80