# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-prediction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: churn-prediction
  template:
    metadata:
      labels:
        app: churn-prediction
    spec:
      containers:
      - name: churn-prediction-container
        image: karan842/churn-prediction:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80